export const DEFAULT_SLOGANS: string[] = [
	"For the stories waiting to be told",
	"Tastes Like Fine Wine",
	"aaaaaaaaaaaaaaaaa",
	"Thanks for the cookies!",
	"Sample Text",
	"Not Batman. Seriously.",
	"Writer? I hardly even know ‘er!",
	"Originally part of a larger publication",
	"We may or may not be Futurama fans",
	"Acquitted by a Jury of Our Peers",
	`Crime-free since ${new Date().toLocaleString()}`,
	"May contain nuts",
	"On-Brand",
	`Don't think about it too hard`,
	"Find the Comic Sans and Win a Prize",
	"There is no dress code",
	"Our slogan changes every 5 seconds",
	"No, we don't have a Hugo",
	"At World's End",
	"Founded on Spite",
	"The Future of Fiction’s Past, Today!",
	"Onprint. Offprint. Onprint. Offprint.",
	"Fanfics will continue until morale improves",
	"Hire a wizard!",
	"Here be dragons",
	"Watch out for stairs!",
	"I got 99 problems but offprint ain't one",
	"Word salad!",
	"Dev team needs coffee",
	"The cake is a lie",
	"Free hugs!",
	"Deluxe hugs $2",
	"Do the thing, win the points",
	"Publishing since 2020",
	"May cause side-effects",
	"The beans are under the milk",
	"Call your mother!",
	"Save a tree, eat a beaver",
	"We met in a tavern!",
	"When in doubt, hug it out",
	"Do not feed after midnight",
	"[This space intentionally left blank]",
	'Quoth the lemming: "Geronimo!"',
	"For honor and glory and stuff",
	"Beware of rabbit",
	"Make a saving throw!",
	"I cast Magic Missile at the darkness",
	"[incoherent screaming]",
	"[screams in French]",
	"*confused Australian noises*",
	"Need help finding anything?",
	"What are you looking for today?",
	"Let's find something you'll love.",
	"Need a hand?",
	"Offprint's got you covered.",
	"Only the best for a connoisseur like you."
];

export const EASTER_SLOGANS: string[] = [];

export const HALLOWEEN_SLOGANS: string[] = [];

export const HOLIDAY_SLOGANS: string[] = [];
