//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(EnumIter, DeriveActiveEnum, Debug, Clone, PartialEq, Eq)]
#[sea_orm(rs_type = "String", db_type = "String(Some(32))")]
pub enum Roles {
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "Moderator")]
    Moderator,
    #[sea_orm(string_value = "WorkApprover")]
    WorkApprover,
    #[sea_orm(string_value = "ChatModerator")]
    ChatModerator,
    #[sea_orm(string_value = "Contributor")]
    Contributor,
    #[sea_orm(string_value = "User")]
    User,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub roles: Vec<Roles>,
    pub terms_agree: bool,
    pub email_confirmed: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
