//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use chrono::offset::Utc;
use sea_orm::ActiveValue::Set;
use sea_orm::entity::prelude::*;
use sea_orm::IntoActiveModel;
use sea_orm::prelude::async_trait::async_trait;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub roles: Vec<String>,
    pub terms_agree: bool,
    pub email_confirmed: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::session::Entity")]
    Session,
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Session.def()
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn after_save<C>(model: Model, db: &C, insert: bool) -> Result<Model, DbErr> where C: ConnectionTrait {
        if insert {
            return Ok(model);
        }
        
        let mut account = model.into_active_model();
        account.updated_at = Set(Utc::now().into());
        let model = account.update(db).await?;
        Ok(model)
    }
}
